site_name: TapCast Docs
theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - content.code.copy
plugins:
  - search

exclude_docs: |
  adr/_template.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences