// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/m1kus3q/pubpredictor/backend/internal/client/weather (interfaces: WeatherClient)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=internal/scheduler/mocks/weather_client_mock.go github.com/m1kus3q/pubpredictor/backend/internal/client/weather WeatherClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	weather "github.com/m1kus3q/pubpredictor/backend/internal/client/weather"
	gomock "go.uber.org/mock/gomock"
)

// MockWeatherClient is a mock of WeatherClient interface.
type MockWeatherClient struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherClientMockRecorder
	isgomock struct{}
}

// MockWeatherClientMockRecorder is the mock recorder for MockWeatherClient.
type MockWeatherClientMockRecorder struct {
	mock *MockWeatherClient
}

// NewMockWeatherClient creates a new mock instance.
func NewMockWeatherClient(ctrl *gomock.Controller) *MockWeatherClient {
	mock := &MockWeatherClient{ctrl: ctrl}
	mock.recorder = &MockWeatherClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherClient) EXPECT() *MockWeatherClientMockRecorder {
	return m.recorder
}

// FetchCurrentWeather mocks base method.
func (m *MockWeatherClient) FetchCurrentWeather(ctx context.Context, lat, lon float64) (*weather.CurrentWeatherSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCurrentWeather", ctx, lat, lon)
	ret0, _ := ret[0].(*weather.CurrentWeatherSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCurrentWeather indicates an expected call of FetchCurrentWeather.
func (mr *MockWeatherClientMockRecorder) FetchCurrentWeather(ctx, lat, lon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCurrentWeather", reflect.TypeOf((*MockWeatherClient)(nil).FetchCurrentWeather), ctx, lat, lon)
}

// FetchFutureWeather mocks base method.
func (m *MockWeatherClient) FetchFutureWeather(ctx context.Context, lat, lon float64, days int) ([]weather.WeatherSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFutureWeather", ctx, lat, lon, days)
	ret0, _ := ret[0].([]weather.WeatherSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFutureWeather indicates an expected call of FetchFutureWeather.
func (mr *MockWeatherClientMockRecorder) FetchFutureWeather(ctx, lat, lon, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFutureWeather", reflect.TypeOf((*MockWeatherClient)(nil).FetchFutureWeather), ctx, lat, lon, days)
}

// FetchHistoricalWeather mocks base method.
func (m *MockWeatherClient) FetchHistoricalWeather(ctx context.Context, lat, lon float64, startDate, endDate time.Time) ([]weather.WeatherSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchHistoricalWeather", ctx, lat, lon, startDate, endDate)
	ret0, _ := ret[0].([]weather.WeatherSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchHistoricalWeather indicates an expected call of FetchHistoricalWeather.
func (mr *MockWeatherClientMockRecorder) FetchHistoricalWeather(ctx, lat, lon, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchHistoricalWeather", reflect.TypeOf((*MockWeatherClient)(nil).FetchHistoricalWeather), ctx, lat, lon, startDate, endDate)
}
